/**
 * Root.jsx
 *
 * Handles:
 *  - Auth gate: show LoginPage if Supabase is configured and user not logged in
 *  - Injects the storage abstraction into window.storage so App.jsx works
 *    unchanged whether Supabase is configured or not
 *  - On first login by the owner account, seeds Supabase with their personal
 *    data exported from the Claude artifact (ownerSeed.json)
 */

import React, { useEffect, useState } from 'react'
import { useAuth } from './AuthContext'
import { loadData, saveData } from './storage'
import LoginPage from './LoginPage'
import App from './App'
import { supabase } from './supabase'

export default function Root() {
  const { user, loading } = useAuth()
  const [seeding, setSeeding] = useState(false)

  // Inject window.storage shim that the App component uses internally.
  useEffect(() => {
    if (loading) return
    const userId = user?.id ?? null

    window.storage = {
      async get(key) {
        const data = await loadData(userId)
        if (!data) return null
        return { key, value: typeof data === 'string' ? data : JSON.stringify(data) }
      },
      async set(key, value) {
        const parsed = (() => {
          try { return JSON.parse(value) } catch { return value }
        })()
        await saveData(userId, parsed)
        return { key, value }
      },
      async delete(key) { return { key, deleted: true } },
      async list() { return { keys: [] } },
    }
  }, [user, loading])

  // On first login by the owner, seed their personal data from ownerSeed.json
  // This file is generated by the artifact's "Download backup" button.
  useEffect(() => {
    if (!user || !supabase) return
    const ownerEmail = import.meta.env.VITE_OWNER_EMAIL
    if (!ownerEmail || user.email !== ownerEmail) return

    ;(async () => {
      // Check if the owner already has data in Supabase
      const existing = await loadData(user.id)
      if (existing && existing.snapshots && existing.snapshots.length > 0) return
      // No data yet — try to seed from ownerSeed.json
      try {
        const res = await fetch('/ownerSeed.json')
        if (!res.ok) return // file not present — skip silently
        const seed = await res.json()
        if (!seed || !seed.snapshots) return
        setSeeding(true)
        await saveData(user.id, seed)
        // Reload so App picks up the freshly seeded data
        window.location.reload()
      } catch (e) {
        console.warn('Owner seed import failed:', e.message)
        setSeeding(false)
      }
    })()
  }, [user])

  if (loading || seeding) {
    return (
      <div style={{ minHeight: '100vh', background: '#fbf8f4', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', fontFamily: 'system-ui', color: '#8a8178', fontSize: 14, gap: 12 }}>
        <div>{seeding ? 'Importing your data…' : 'Loading…'}</div>
        {seeding && <div style={{ fontSize: 12 }}>This only happens once on first login.</div>}
      </div>
    )
  }

  if (supabase && !user) return <LoginPage />

  return <App />
}
